name: Build Windows and macOS test artifacts

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    with:
      publish: false
